In [1]:
pip install pdfkit

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import pandas as pd
from sklearn.impute import  SimpleImputer as si
#from sklearn.preprocessing import Imputer ------also used



In [3]:
  df = pd.DataFrame()

df['C0'] = [0.2601,0.2358,0.1429,0.1259,0.7526,
                0.7341,0.4546,0.1426,0.1490,0.2500]
df['C1'] = [0.7154,np.nan,0.2615,0.5846,np.nan,
                0.8308,0.4962,np.nan,0.5340,0.6731]
df["C3"] = [0.7154,np.nan,0.2615,0.5846,np.nan,
                0.8308,0.4962,np.nan,0.5340,0.6731]

df["C4"]=["a","b","c","d","f","g","h","i","j","k"]
df["C4"]=["a","b",np.nan,"d","f",np.nan,"h","i","j",np.nan]
print(df)

       C0      C1      C3   C4
0  0.2601  0.7154  0.7154    a
1  0.2358     NaN     NaN    b
2  0.1429  0.2615  0.2615  NaN
3  0.1259  0.5846  0.5846    d
4  0.7526     NaN     NaN    f
5  0.7341  0.8308  0.8308  NaN
6  0.4546  0.4962  0.4962    h
7  0.1426     NaN     NaN    i
8  0.1490  0.5340  0.5340    j
9  0.2500  0.6731  0.6731  NaN


In [4]:
x_df=df.drop(columns="C0")

In [5]:
y_df=df["C0"]

In [6]:
print("Dimension of Train ", x_df.shape)
print("Dimension of Test ", y_df.shape)

Dimension of Train  (10, 3)
Dimension of Test  (10,)


In [7]:
num_var=x_df.select_dtypes(include=["int64","float64"]).columns#select the int col from new x_df 

In [8]:
num_var

Index(['C1', 'C3'], dtype='object')

In [9]:
x_df[num_var].isnull().sum()

C1    3
C3    3
dtype: int64

In [10]:
imputer_mean=si(strategy='mean')#impport for centerral tendancy

In [11]:
imputer_mean.fit(df[num_var])

SimpleImputer()

In [12]:
imputer_mean.statistics_

array([0.58508571, 0.58508571])

In [13]:
x_df[num_var]=imputer_mean.transform(df[num_var])#take each val mean

In [14]:
x_df[num_var].isnull().sum()

C1    0
C3    0
dtype: int64

In [15]:
cat_var=x_df.select_dtypes(include="O").columns

In [16]:
cat_var

Index(['C4'], dtype='object')

In [17]:
x_df[cat_var].isnull().sum()

C4    3
dtype: int64

In [18]:
imputer_mode=si(strategy='most_frequent')

In [19]:
imputer_mode

SimpleImputer(strategy='most_frequent')

In [20]:
imputer_mode.fit(x_df[cat_var])

SimpleImputer(strategy='most_frequent')

In [21]:
imputer_mode.transform(x_df[cat_var])

array([['a'],
       ['b'],
       ['a'],
       ['d'],
       ['f'],
       ['a'],
       ['h'],
       ['i'],
       ['j'],
       ['a']], dtype=object)

In [22]:
imputer_mode.statistics_

array(['a'], dtype=object)

In [23]:
x_df[cat_var]=imputer_mode.fit_transform(x_df[cat_var])

In [24]:
x_df[cat_var].isnull().sum()

C4    0
dtype: int64

# load new dataset

In [25]:
import seaborn as sns

In [26]:
tips=sns.load_dataset("titanic")

In [27]:
tips.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [28]:
tips.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [29]:
x_tips=tips.drop(columns="age")
y_tips=tips["age"]

In [30]:
    print("Dimension of Train ", x_tips.shape)
    print("Dimension of Test ", y_tips.shape)

Dimension of Train  (891, 14)
Dimension of Test  (891,)


In [31]:
num_vars=x_tips.select_dtypes(include=["int64","float64"]).columns

In [32]:
num_vars

Index(['survived', 'pclass', 'sibsp', 'parch', 'fare'], dtype='object')

In [33]:
x_tips[num_vars].isnull().sum()

survived    0
pclass      0
sibsp       0
parch       0
fare        0
dtype: int64

In [34]:
impute_mean=si(missing_values=np.nan,strategy="mean")

In [35]:
impute_mean.fit(x_tips[num_vars])

SimpleImputer()

In [36]:
impute_mean.statistics_

array([ 0.38383838,  2.30864198,  0.52300786,  0.38159371, 32.20420797])

In [37]:
impute_mean.transform(x_tips[num_vars])

array([[ 0.    ,  3.    ,  1.    ,  0.    ,  7.25  ],
       [ 1.    ,  1.    ,  1.    ,  0.    , 71.2833],
       [ 1.    ,  3.    ,  0.    ,  0.    ,  7.925 ],
       ...,
       [ 0.    ,  3.    ,  1.    ,  2.    , 23.45  ],
       [ 1.    ,  1.    ,  0.    ,  0.    , 30.    ],
       [ 0.    ,  3.    ,  0.    ,  0.    ,  7.75  ]])

In [38]:
x_tips[num_vars]=impute_mean.transform(x_tips[num_vars])

In [39]:
x_tips[num_vars].isnull().sum()

survived    0
pclass      0
sibsp       0
parch       0
fare        0
dtype: int64

In [40]:
cat_vars=x_tips.select_dtypes(include=["category","O"]).columns

In [41]:
cat_vars

Index(['sex', 'embarked', 'class', 'who', 'deck', 'embark_town', 'alive'], dtype='object')

In [42]:
x_tips[cat_vars].isnull().sum()

sex              0
embarked         2
class            0
who              0
deck           688
embark_town      2
alive            0
dtype: int64

In [43]:
imputer_mode=si(strategy='most_frequent')

In [44]:
imputer_mode

SimpleImputer(strategy='most_frequent')

In [45]:
imputer_mode.fit(x_tips[cat_vars])

SimpleImputer(strategy='most_frequent')

In [46]:
imputer_mode.transform(x_tips[cat_vars])

array([['male', 'S', 'Third', ..., 'C', 'Southampton', 'no'],
       ['female', 'C', 'First', ..., 'C', 'Cherbourg', 'yes'],
       ['female', 'S', 'Third', ..., 'C', 'Southampton', 'yes'],
       ...,
       ['female', 'S', 'Third', ..., 'C', 'Southampton', 'no'],
       ['male', 'C', 'First', ..., 'C', 'Cherbourg', 'yes'],
       ['male', 'Q', 'Third', ..., 'C', 'Queenstown', 'no']], dtype=object)

In [47]:
x_tips[cat_vars]=imputer_mode.transform(x_tips[cat_vars])

In [48]:
x_tips[cat_vars].isnull().sum()

sex            0
embarked       0
class          0
who            0
deck           0
embark_town    0
alive          0
dtype: int64

In [49]:
x_tips.isnull().sum().sum()

0

In [50]:
x_tips

survived  pclass     sex  sibsp  parch     fare embarked   class    who  \
0         0.0     3.0    male    1.0    0.0   7.2500        S   Third    man   
1         1.0     1.0  female    1.0    0.0  71.2833        C   First  woman   
2         1.0     3.0  female    0.0    0.0   7.9250        S   Third  woman   
3         1.0     1.0  female    1.0    0.0  53.1000        S   First  woman   
4         0.0     3.0    male    0.0    0.0   8.0500        S   Third    man   
..        ...     ...     ...    ...    ...      ...      ...     ...    ...   
886       0.0     2.0    male    0.0    0.0  13.0000        S  Second    man   
887       1.0     1.0  female    0.0    0.0  30.0000        S   First  woman   
888       0.0     3.0  female    1.0    2.0  23.4500        S   Third  woman   
889       1.0     1.0    male    0.0    0.0  30.0000        C   First    man   
890       0.0     3.0    male    0.0    0.0   7.7500        Q   Third    man   

     adult_male deck  embark_town alive  alone  
0          True    C  Southampton    no  False  
1         False    C    Cherbourg   yes  False  
2         False    C  Southampton   yes   True  
3         False    C  Southampton   yes  False  
4          True    C  Southampton    no   True  
..          ...  ...          ...   ...    ...  
886        True    C  Southampton    no   True  
887       False    B  Southampton   yes   True  
888       False    C  Southampton    no  False  
889        True    C    Cherbourg   yes   True  
890        True    C   Queenstown    no   True  

[891 rows x 14 columns]